# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

if [[ -z "${WT_SHELL_INTEGRATION_POSIX_ROOT:-}" ]]; then
    return
fi

typeset -g WT_SHELL_INTEGRATION_PROXY_ZDOTDIR="$WT_SHELL_INTEGRATION_POSIX_ROOT/zsh"
typeset -g WT_SHELL_INTEGRATION_USER_ZDOTDIR="${WT_SHELL_INTEGRATION_USER_ZDOTDIR:-${ZDOTDIR:-$HOME}}"

if [[ -z "${WT_SHELL_INTEGRATION_ZSHENV_LOADED:-}" ]]; then
    export WT_SHELL_INTEGRATION_ZSHENV_LOADED=1
    ZDOTDIR="$WT_SHELL_INTEGRATION_USER_ZDOTDIR"
    [[ -r "$ZDOTDIR/.zshenv" ]] && source "$ZDOTDIR/.zshenv"
    WT_SHELL_INTEGRATION_USER_ZDOTDIR="${ZDOTDIR:-$HOME}"
fi

ZDOTDIR="$WT_SHELL_INTEGRATION_PROXY_ZDOTDIR"
