// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.TerminalConnection
{
    enum ConnectionState
    {
        NotConnected = 0,
        Connecting,
        Connected,
        Closing,
        Closed,
        Failed
    };

    enum ShellIntegrationEnvironmentKind
    {
        Unsupported = 0,
        LocalWindows = 1,
        Wsl = 2
    };

    delegate void TerminalOutputHandler(Char[] output);

    interface ITerminalConnection
    {
        void Initialize(Windows.Foundation.Collections.ValueSet settings);

        void Start();
        void WriteInput(Char[] data);
        void Resize(UInt32 rows, UInt32 columns);
        void Close();

        event TerminalOutputHandler TerminalOutput;
        event Windows.Foundation.TypedEventHandler<ITerminalConnection, Object> StateChanged;

        Guid SessionId { get; };
        ConnectionState State { get; };
    };

    interface IShellIntegrationConnectionInfo
    {
        Boolean ShellIntegrationEnabled { get; };
        ShellIntegrationEnvironmentKind ShellIntegrationEnvironment { get; };
        String ShellIntegrationWslDistro { get; };
        String ShellIntegrationWslUser { get; };
        String ShellIntegrationAssetRoot { get; };
    };
}
