// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

#pragma once

#include <atomic>
#include <chrono>
#include <functional>
#include <filesystem>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>
#include <json/json.h>

namespace TerminalApp::GitHub
{
    enum class Failure
    {
        None,
        MissingCli,
        Request,
        Timeout,
        InvalidResponse,
        AccountChanged,
        Cancelled
    };

    struct Error : std::exception
    {
        explicit Error(Failure value) noexcept : failure{ value } {}
        Failure failure;
    };

    struct Check
    {
        std::string name;
        std::string state;
    };

    struct Item
    {
        std::string title;
        std::string repository;
        std::string url;
        std::string updatedAt;
        std::string description;
        std::string activityKind;
        std::string state;
        std::string author;
        std::string avatarUrl;
        std::string head;
        std::string base;
        std::string review;
        std::vector<std::string> labels;
        std::vector<Check> checks;
        uint32_t number{};
        uint32_t comments{};
        uint32_t labelCount{};
        uint32_t checkCount{};
        uint32_t events{};
    };

    struct Day
    {
        std::string date;
        uint32_t weekday{};
        uint32_t count{};
        uint32_t level{};
        uint32_t week{};
    };

    struct Calendar
    {
        uint32_t total{};
        std::vector<Day> days;
    };

    struct Quota
    {
        std::string kind;
        bool credits{};
        bool unlimited{};
        bool included{ true };
        std::optional<double> used;
        std::string reset;
    };

    struct Usage
    {
        std::string plan;
        std::vector<Quota> quotas;
    };

    template<typename T>
    struct Section
    {
        std::optional<T> value;
        std::chrono::system_clock::time_point updated{};
        Failure failure{ Failure::None };
    };

    struct Snapshot
    {
        std::string id;
        std::string login;
        std::string name;
        std::string avatarUrl;
        Section<std::vector<Item>> activity;
        Section<std::vector<Item>> pulls;
        Section<std::vector<Item>> reviews;
        Section<std::vector<Item>> repos;
        Section<Calendar> calendar;
        Section<Usage> usage;
    };

    bool IsSectionExpired(std::chrono::system_clock::time_point updated,
                          std::chrono::system_clock::time_point now = std::chrono::system_clock::now()) noexcept;
    void ExpireSections(Snapshot& snapshot,
                        std::chrono::system_clock::time_point now = std::chrono::system_clock::now());

    // The transport accepts only read operations generated by this module.
    using Request = std::function<Json::Value(const std::string& endpoint, const std::string& query)>;
    Json::Value ReadApi(const std::string& endpoint, const std::string& query, const std::atomic<bool>& cancelled);
    enum class RefreshReason
    {
        Manual,
        Automatic
    };
    using Update = std::function<void(const Snapshot&)>;
    Snapshot Refresh(const Request& request, const Snapshot& previous, RefreshReason reason = RefreshReason::Manual, const Update& update = {});
    Snapshot ReadCache(const std::filesystem::path& path);
    std::filesystem::path CachePath();
    void WriteCache(const std::filesystem::path& path, const Snapshot& snapshot);
    Json::Value SerializeCache(const Snapshot& snapshot);
    Snapshot DeserializeCache(const Json::Value& value);
    Item ParsePullRequest(const Json::Value& value);
    Snapshot ParseIdentity(const Json::Value& value);
    Calendar ParseCalendar(const Json::Value& value);
    Usage ParseUsage(const Json::Value& value, const std::string& login);
    bool IsGitHubUrl(const std::string& url) noexcept;
    bool IsGitHubAvatarUrl(const std::string& url) noexcept;
}
